[package]
name = "SolanaRustBootCamp2024"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.9"  # Use the latest version available
borsh = "1.5.1"  # Ensure borsh is also included
serde_json = "1.0"
